### ISSUE TITLE
Cannot open downloaded files

### ISSUE THREAD

**Issue by Valansch** [kamalagbaria/URLDownloader#2]
When running the download I cannot open the files after downloading

**Steps to reproduce**
1. Create file `images`:
```
https://picsum.photos/536/354
https://picsum.photos/323/531
https://picsum.photos/512/512
```

2. Run downloader
3. Click to open image

**Expected behaviour**
It opens the image
**Actual behaviour**
`There is no application set to open the document “354.jpg?hmac=zcBiVT7i6DxsumWqwd7Vr_02wXb3mJCz9wSjIqdEIJk”`

**Comment by kamalagbaria** [comment]
Issue is fixed, Please try again now.
